framework:
    messenger:
        failure_transport: failed

        transports:
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: email_notifications
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            App\Message\OrderCreatedMessage: async
            App\Message\OrderStatusChangedMessage: async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
