version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_XDEBUG: "0"
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@postgres:5432/app?serverVersion=16&charset=utf8"
      MESSENGER_TRANSPORT_DSN: "doctrine://default?auto_setup=1"
    depends_on:
      - postgres

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d app || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  pgdata:
